Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 16:13:39
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 16:13:47] "GET /portal/create/ HTTP/1.1" 200 10233
[12/Dec/2016 16:13:47] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 16:13:47] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 16:13:47] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 16:13:47] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 16:13:47] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 16:13:47] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 16:13:47] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 16:13:47] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 16:13:47] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 16:13:47] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 16:13:47] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 16:13:48] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 16:13:48] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 16:13:48] "GET /static/img/logo.png HTTP/1.1" 200 18815
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 16:13:45
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 16:28:04] "POST /portal/create/ HTTP/1.1" 302 0
[12/Dec/2016 16:28:04] "GET /portal/edit/8 HTTP/1.1" 200 10462
[12/Dec/2016 16:28:04] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/css/main.css HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 16:28:04] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 16:28:04] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[12/Dec/2016 16:28:04] "GET /static/img/logo.png HTTP/1.1" 304 0
[12/Dec/2016 16:28:42] "GET /portal/ HTTP/1.1" 200 12539
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 16:13:51
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 16:32:48] "GET /portal/ HTTP/1.1" 200 12611
[12/Dec/2016 16:32:48] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 16:32:48] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 16:32:48] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 16:32:48] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 16:32:48] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 16:32:48] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 16:32:48] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 16:32:48] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 16:32:48] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 16:32:48] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 16:32:48] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 16:32:48] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[12/Dec/2016 16:32:48] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 16:32:48] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 16:32:48] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 16:32:48] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 16:32:51] "GET /portal/6 HTTP/1.1" 200 10363
[12/Dec/2016 16:32:51] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/css/main.css HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 16:32:51] "GET /static/img/logo.png HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 16:32:46
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 16:32:51
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 16:33:08] "GET /portal/ HTTP/1.1" 200 12003
[12/Dec/2016 16:33:08] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 16:33:08] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 16:33:08] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 16:33:08] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 16:33:08] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 16:33:08] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 16:33:08] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 16:33:08] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 16:33:08] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 16:33:08] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:08] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 16:33:08] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 16:33:08] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 16:33:08] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[12/Dec/2016 16:33:08] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 16:33:08] "GET /portal HTTP/1.1" 301 0
[12/Dec/2016 16:33:08] "GET /portal/ HTTP/1.1" 200 12003
[12/Dec/2016 16:33:08] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[12/Dec/2016 16:33:08] "GET /static/css/prettyPhoto.css HTTP/1.1" 200 19930
[12/Dec/2016 16:33:08] "GET /static/css/main.css HTTP/1.1" 200 9160
[12/Dec/2016 16:33:08] "GET /static/css/owl.carousel.css HTTP/1.1" 200 3149
[12/Dec/2016 16:33:08] "GET /static/css/animate.css HTTP/1.1" 200 59839
[12/Dec/2016 16:33:08] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 116743
[12/Dec/2016 16:33:08] "GET /static/css/responsive.css HTTP/1.1" 200 1013
[12/Dec/2016 16:33:08] "GET /static/js/plugins.js HTTP/1.1" 200 733
[12/Dec/2016 16:33:08] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[12/Dec/2016 16:33:08] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 200 15414
[12/Dec/2016 16:33:08] "GET /static/js/wow.min.js HTTP/1.1" 200 7083
[12/Dec/2016 16:33:08] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 200 93107
[12/Dec/2016 16:33:08] "GET /static/js/owl.carousel.min.js HTTP/1.1" 200 23890
[12/Dec/2016 16:33:08] "GET /static/js/main.js HTTP/1.1" 200 1554
[12/Dec/2016 16:33:08] "GET /static/js/prettyPhoto.js HTTP/1.1" 200 22060
[12/Dec/2016 16:33:08] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 16:33:08] "GET /static/img/logo.png HTTP/1.1" 200 18815
[12/Dec/2016 16:33:10] "GET /portal/6 HTTP/1.1" 200 10363
[12/Dec/2016 16:33:10] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/css/main.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:10] "GET /static/img/logo.png HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 16:33:06
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[12/Dec/2016 16:33:53] "GET /portal/7 HTTP/1.1" 200 10360
[12/Dec/2016 16:33:53] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/css/animate.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/css/prettyPhoto.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/css/owl.carousel.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/css/main.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/css/responsive.css HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/js/vendor/modernizr-2.6.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/js/vendor/jquery-1.10.2.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/js/plugins.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/js/wow.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/js/prettyPhoto.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/js/main.js HTTP/1.1" 304 0
[12/Dec/2016 16:33:53] "GET /static/img/logo.png HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
December 12, 2016 - 16:33:12
Django version 1.10, using settings 'RCBuilder.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f682465ea60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 10, in <module>
    from .forms import RCForm, TargetFormSet
  File "/etc/side_projects/RCBuilder/rcapp/forms.py", line 18, in <module>
    TargetFormSet = inlineformset_factory(ResultsChain, Target, form=TargetForm, extra=1, fk_name='resultschain')
NameError: name 'inlineformset_factory' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f2f10543c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 10, in <module>
    from .forms import RCForm, TargetFormSet
  File "/etc/side_projects/RCBuilder/rcapp/forms.py", line 18, in <module>
    TargetFormSet = inlineformset_factory(ResultsChain, Target, form=TargetForm, extra=1, fk_name='resultschain')
NameError: name 'inlineformset_factory' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f3d973e0a60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 10, in <module>
    from .forms import RCForm, TargetFormSet
  File "/etc/side_projects/RCBuilder/rcapp/forms.py", line 18, in <module>
    TargetFormSet = inlineformset_factory(ResultsChain, Target, form=TargetForm, extra=1, fk_name='resultschain')
NameError: name 'inlineformset_factory' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fbef55afc80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 10, in <module>
    from .forms import RCForm, TargetFormSet
  File "/etc/side_projects/RCBuilder/rcapp/forms.py", line 18, in <module>
    TargetFormSet = inlineformset_factory(ResultsChain, Target, form=TargetForm, extra=1, fk_name='resultschain')
NameError: name 'inlineformset_factory' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f1a46c22c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 10, in <module>
    from .forms import RCForm, TargetFormSet
  File "/etc/side_projects/RCBuilder/rcapp/forms.py", line 18, in <module>
    TargetFormSet = inlineformset_factory(ResultsChain, Target, form=TargetForm, extra=1, fk_name='resultschain')
  File "/usr/local/lib/python3.4/dist-packages/django/forms/models.py", line 1029, in inlineformset_factory
    fk = _get_foreign_key(parent_model, model, fk_name=fk_name)
  File "/usr/local/lib/python3.4/dist-packages/django/forms/models.py", line 984, in _get_foreign_key
    "'%s' has no field named '%s'." % (model._meta.label, fk_name)
ValueError: 'rcapp.Target' has no field named 'resultschain'.
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f64ae550c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 10, in <module>
    from .forms import RCForm, TargetFormSet
  File "/etc/side_projects/RCBuilder/rcapp/forms.py", line 18, in <module>
    TargetFormSet = inlineformset_factory(ResultsChain, Target, form=TargetForm, extra=1, fk_name='resultschain')
  File "/usr/local/lib/python3.4/dist-packages/django/forms/models.py", line 1029, in inlineformset_factory
    fk = _get_foreign_key(parent_model, model, fk_name=fk_name)
  File "/usr/local/lib/python3.4/dist-packages/django/forms/models.py", line 984, in _get_foreign_key
    "'%s' has no field named '%s'." % (model._meta.label, fk_name)
ValueError: 'rcapp.Target' has no field named 'resultschain'.
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7febfe894ae8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 10, in <module>
    from .forms import RCForm, TargetFormSet
  File "/etc/side_projects/RCBuilder/rcapp/forms.py", line 18, in <module>
    TargetFormSet = inlineformset_factory(ResultsChain, Target, form=TargetForm, extra=1, fk_name='resultschain')
  File "/usr/local/lib/python3.4/dist-packages/django/forms/models.py", line 1029, in inlineformset_factory
    fk = _get_foreign_key(parent_model, model, fk_name=fk_name)
  File "/usr/local/lib/python3.4/dist-packages/django/forms/models.py", line 984, in _get_foreign_key
    "'%s' has no field named '%s'." % (model._meta.label, fk_name)
ValueError: 'rcapp.Target' has no field named 'resultschain'.
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f4b30933c80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/RCBuilder/urls.py", line 25, in <module>
    url(r'^portal/', include('rcapp.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/etc/side_projects/RCBuilder/rcapp/urls.py", line 3, in <module>
    from . import views
  File "/etc/side_projects/RCBuilder/rcapp/views.py", line 10, in <module>
    from .forms import RCForm, TargetFormSet
  File "/etc/side_projects/RCBuilder/rcapp/forms.py", line 18, in <module>
    TargetFormSet = inlineformset_factory(ResultsChain, Target, form=TargetForm, extra=1, fk_name='resultschain')
  File "/usr/local/lib/python3.4/dist-packages/django/forms/models.py", line 1029, in inlineformset_factory
    fk = _get_foreign_key(parent_model, model, fk_name=fk_name)
  File "/usr/local/lib/python3.4/dist-packages/django/forms/models.py", line 984, in _get_foreign_key
    "'%s' has no field named '%s'." % (model._meta.label, fk_name)
ValueError: 'rcapp.Target' has no field named 'resultschain'.
Performing system checks...

